markdown: pandoc
pandoc: 
  extensions: [mathjax, standalone]
lunr_search:
  js_dir: "media/js"
permalink: /:year/:month/:title/
url: http://blog.tonytsai.name
author: Tony Tsai
gems: [jekyll-paginate]
paginate: 24

exclude: ["README.md", "LICENSE"]